name: "Machinefile executor"
description: "A simple Dockerfile/Containerfile interpreter to set up the local machine"
author: "Gerard Braad <me@gbraad.nl>"
inputs:
  containerfile:
    description: 'Path to the Dockerfile/Containerfile to execute'
    required: true
    default: 'Containerfile'
  context:
    description: 'Directory to use as build context'
    required: true
    default: '.'
  arguments:
    description: 'Additional arguments to pass to the machinefile tool (e.g., --arg=USERID=1000 --arg=HOMEBASE=/var/home)'
    required: false
    default: ''
  binarypath:
    description: 'Path to the machinefile binary'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Setup Machinefile executor
      id: setup
      shell: bash
      run: |
        VERSION=0.3.0
        DOWNLOAD_BASEURL="https://github.com/gbraad-redhat/Machinefile/releases/download/${VERSION}"

        if [[ -z "${{ inputs.binarypath }}" ]]; then
          arch=$(uname -m)
          if [[ "$arch" == "x86_64" ]]; then
            DOWNLOAD_URL="${DOWNLOAD_BASEURL}/linux-amd64.tar.gz"
          elif [[ "$arch" == "aarch64" ]]; then
            DOWNLOAD_URL="${DOWNLOAD_BASEURL}/linux-arm64.tar.gz"
          else
            echo "::error::Unsupported architecture: $arch. Only x86_64 and aarch64 are supported."
            exit 1
          fi

          echo "Downloading Machinefile executor from $DOWNLOAD_URL"
          mkdir -p /tmp/machinefile-executor
          curl -sSL $DOWNLOAD_URL | tar -xz -C /tmp/machinefile-executor --strip-components=1
          chmod +x /tmp/machinefile-executor/machinefile
          BINARY_PATH="/tmp/machinefile-executor/machinefile"
          echo "Downloaded and extracted Machinefile executor binary"
        else
          BINARY_PATH="${{ inputs.binarypath }}"
          echo "Using specified binary path: $BINARY_PATH"
        fi

        echo "MACHINEFILE=$BINARY_PATH" >> $GITHUB_ENV

    - name: Execute Containerfile commands
      shell: bash
      run: |
        echo "Running Containerfile: ${{ inputs.containerfile }}"
        echo "Context directory: ${{ inputs.context }}"
        sudo $MACHINEFILE ${{ inputs.arguments }} "${{ inputs.containerfile }}" "${{ inputs.context }}"

